#!/usr/bin/env node
/**
 * Emits the landing page's design-system assets.
 *
 * The landing lives in public/, outside the bundle and outside the service worker, so it
 * cannot `@import` design-system/tokens/tokens.css the way src/index.css does. The obvious
 * workaround is what public/calculadoras/ did: hand-copy a :root block. That block is now
 * stale — it still declares Inter Variable and --color-tax, both retired in August — which
 * is exactly the debt design-system/docs/00-principles.md §A1 warns about.
 *
 * So nothing is copied by hand. This script mirrors the generated token file and the font
 * binaries verbatim, and `--check` fails when the mirror has drifted. Same shape as the
 * repo validator's R2.
 *
 * It also stamps the CSS and JS links of the landing and the calculator page with a content hash
 * (`/landing/styles.css?v=1a2b3c4d`). GitHub Pages serves them with `Cache-Control: max-age=600`
 * under names that never change, so for ten minutes after a deploy a returning visitor got the
 * new HTML with the old stylesheet — a fix shipped, verified live, and invisible on the phone of
 * the person who asked for it. A changed file is a changed URL, so it is fetched at once.
 * `--check` fails when a stamp no longer matches its file.
 *
 * Usage: node scripts/landing-assets.mjs [--check]
 */
import { readFileSync, writeFileSync, copyFileSync, mkdirSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const check = process.argv.includes('--check')

const TOKENS_SRC = join(root, 'design-system/tokens/tokens.css')
const TOKENS_OUT = join(root, 'public/landing/tokens.css')

// Only the Latin subsets. The landing is es-CO; latin-ext covers the accents Spanish
// actually uses and the rest would be weight the page never serves.
const FONTS = ['rethink-sans-latin-wght-normal.woff2', 'rethink-sans-latin-ext-wght-normal.woff2']
const FONT_SRC_DIR = join(root, 'node_modules/@fontsource-variable/rethink-sans/files')
const FONT_OUT_DIR = join(root, 'public/landing/fonts')

const HEADER = `/* GENERATED by scripts/landing-assets.mjs — do not edit by hand.
   Mirror of design-system/tokens/tokens.css, which is itself generated from Figma.
   Run \`node scripts/landing-assets.mjs\` after any token change. */\n\n`

const sha = (buf) => createHash('sha256').update(buf).digest('hex')

const tokens = readFileSync(TOKENS_SRC, 'utf8')
const expected = HEADER + tokens

const drifted = []

if (!existsSync(TOKENS_OUT) || readFileSync(TOKENS_OUT, 'utf8') !== expected) {
  if (check) drifted.push('public/landing/tokens.css')
  else {
    mkdirSync(dirname(TOKENS_OUT), { recursive: true })
    writeFileSync(TOKENS_OUT, expected)
  }
}

mkdirSync(FONT_OUT_DIR, { recursive: true })
for (const file of FONTS) {
  const from = join(FONT_SRC_DIR, file)
  const to = join(FONT_OUT_DIR, file)
  if (!existsSync(from)) {
    console.error(`missing font source: ${from} — run npm ci`)
    process.exit(1)
  }
  if (!existsSync(to) || sha(readFileSync(to)) !== sha(readFileSync(from))) {
    if (check) drifted.push(`public/landing/fonts/${file}`)
    else copyFileSync(from, to)
  }
}

// ── Cache-busting stamps ────────────────────────────────────────────────────────────────
// Hash what is on disk now (tokens.css was just written above when not checking; when checking,
// hash what it SHOULD be, so a drifted mirror and a stale stamp are reported separately).
// Every page that links a landing asset is stamped; a page that links one must link it once.
const ASSETS = {
  'tokens.css': check ? expected : readFileSync(TOKENS_OUT, 'utf8'),
  'styles.css': readFileSync(join(root, 'public/landing/styles.css')),
  'calculadora.css': readFileSync(join(root, 'public/landing/calculadora.css')),
  'main.js': readFileSync(join(root, 'public/landing/main.js')),
}
const PAGES = {
  'public/index.html': ['tokens.css', 'styles.css', 'main.js'],
  'public/calculadoras/seguridad-social-independientes/index.html': ['tokens.css', 'styles.css', 'calculadora.css', 'main.js'],
  'public/calculadoras/index.html': ['tokens.css', 'styles.css', 'calculadora.css', 'main.js'],
}
for (const [rel, files] of Object.entries(PAGES)) {
  const path = join(root, rel)
  const page = readFileSync(path, 'utf8')
  let stamped = page
  for (const file of files) {
    const v = sha(ASSETS[file]).slice(0, 8)
    const re = new RegExp(`"/landing/${file.replace('.', '\\.')}(\\?v=[0-9a-f]+)?"`, 'g')
    const hits = stamped.match(re) || []
    if (hits.length !== 1) {
      console.error(`expected exactly one link to /landing/${file} in ${rel}, found ${hits.length}`)
      process.exit(1)
    }
    stamped = stamped.replace(re, `"/landing/${file}?v=${v}"`)
  }
  if (stamped !== page) {
    if (check) drifted.push(`${rel} (asset version stamps)`)
    else writeFileSync(path, stamped)
  }
}

// ── FAQ structured data, generated from the visible FAQ ───────────────────────────────────
// Google reads FAQPage markup only when it matches what the page shows. The landing's schema was
// hand-written and drifted the day its questions were rewritten (4 of 7 answers no longer on the
// page). So the schema is not written by hand any more: every page with a
// <script type="application/ld+json" data-schema="faq"> gets it rebuilt from its own <details>
// inside .faq, and `--check` fails when the two disagree.
const strip = (html) => html
  .replace(/<svg[\s\S]*?<\/svg>/g, '')
  .replace(/<[^>]+>/g, '')
  .replace(/&nbsp;/g, ' ')
  .replace(/\s+/g, ' ')
  .trim()

for (const rel of Object.keys(PAGES)) {
  const path = join(root, rel)
  const page = readFileSync(path, 'utf8')
  const block = page.match(/( *)<script type="application\/ld\+json" data-schema="faq">[\s\S]*?<\/script>/)
  if (!block) continue
  const faq = page.match(/<div class="faq"[^>]*>([\s\S]*?)\n {10}<\/div>/)
  if (!faq) {
    console.error(`${rel}: has a FAQ schema block but no visible .faq to build it from`)
    process.exit(1)
  }
  const entities = [...faq[1].matchAll(/<details>([\s\S]*?)<\/details>/g)].map(([, d]) => ({
    '@type': 'Question',
    name: strip(d.match(/<summary[^>]*>([\s\S]*?)<\/summary>/)[1]),
    acceptedAnswer: {
      '@type': 'Answer',
      text: [...d.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/g)].map(([, p]) => strip(p)).join(' '),
    },
  }))
  const indent = block[1]
  const json = JSON.stringify({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: entities }, null, 2)
    .split('\n').map((l) => `${indent}  ${l}`).join('\n')
  const rebuilt = `${indent}<script type="application/ld+json" data-schema="faq">\n${json}\n${indent}</script>`
  if (rebuilt !== block[0]) {
    if (check) drifted.push(`${rel} (FAQ schema no longer matches the visible FAQ)`)
    else writeFileSync(path, page.replace(block[0], rebuilt))
  }
}

if (check) {
  if (drifted.length) {
    console.error('landing assets have drifted from their source:')
    for (const f of drifted) console.error(`  ${f}`)
    console.error('fix: node scripts/landing-assets.mjs')
    process.exit(1)
  }
  console.log('landing assets: in sync')
} else {
  console.log(`landing assets: tokens.css + ${FONTS.length} fonts written to public/landing/, pages stamped`)
}
